---
- name: Cisco ios gather facts
  hosts: R1
  
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Print ansible_facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Print device_config
      ansible.builtin.debug:
        msg: "{{ ansible_facts.net_config }}"

    - name: Print device_config with key net_config
      ansible.builtin.debug:
        msg: "{{ ansible_facts['net_config'] }}"

    - name: Print device_config splint into lines
      ansible.builtin.debug:
        msg: "{{ ansible_facts.net_config.split('\n') }}"
