---
- name: IOS backup
  hosts: R1
  gather_facts: false

  tasks:
    # - name: Configure domain name and diff check againt running-config
    #   cisco.ios.ios_config:
    #     lines: ip domain name test1.com
    #     diff_against: running
    #     backup: no
    #     backup_options:
    #       dir_path: ./device_backup/{{ inventory_hostname }}/
    #       filename: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}.txt"
    #   register: router_domain_name

    # - name: Configure domain name and diff check againt startup-config
    #   cisco.ios.ios_config:
    #     lines: ip domain name test1.com
    #     diff_against: startup
    #     backup: no
    #     backup_options:
    #       dir_path: ./device_backup/{{ inventory_hostname }}/
    #       filename: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}.txt"
    #   register: router_domain_name

    # - name: Configure domain name and diff check againt intended config
    #   cisco.ios.ios_config:
    #     lines: ip domain name test.com
    #     diff_against: intended
    #     intended_config: "{{ lookup('file', '/home/dev/git_repo/device_backup/{{ inventory_hostname }}/golden_config/{{ inventory_hostname }}.txt') }}"
    #     backup: false
    #     backup_options:
    #       dir_path: ./device_backup/{{ inventory_hostname }}/
    #       filename: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}.txt"
    #   register: router_domain_name

    - name: Configure domain name and diff check againt intended config but ignore lines
      cisco.ios.ios_config:
        lines: ip domain name test1.com
        diff_against: intended
        intended_config: "{{ lookup('file', '/home/dev/git_repo/device_backup/{{ inventory_hostname }}/golden_config/{{ inventory_hostname }}.txt') }}"
        diff_ignore_lines: 
          - hostname  *
          - ip domain *
        backup: false
        backup_options:
          dir_path: ./device_backup/{{ inventory_hostname }}/
          filename: "{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}.txt"
      register: router_domain_name


    - name: Print router domain name
      ansible.builtin.debug:
        msg: "{{ router_domain_name }}"
