all:
  children:
    routers:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: cisco
        ip_domain_name: inv_file.com
      children:
        group1:
          hosts:
            R1:
        group2:
          hosts:
            R2:
              ip_domain_name: R2.com
    ungrouped:
      hosts:
        localhost:
          ansible_connection: local
